# Generated by Django 5.2.15 on 2026-07-10 07:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


CATEGORIES = (
    ("Technology", "technology"),
    ("Study & Education", "study-education"),
    ("Career", "career"),
    ("Sport", "sport"),
    ("Social", "social"),
    ("Music & Nightlife", "music-nightlife"),
    ("Culture", "culture"),
    ("Other", "other"),
)


def seed_categories(apps, schema_editor):
    Category = apps.get_model("events", "Category")
    Event = apps.get_model("events", "Event")
    categories = {
        slug: Category.objects.get_or_create(name=name, slug=slug)[0]
        for name, slug in CATEGORIES
    }
    Event.objects.filter(category__isnull=True).update(
        category=categories["other"]
    )


def unseed_categories(apps, schema_editor):
    Category = apps.get_model("events", "Category")
    Event = apps.get_model("events", "Event")
    Event.objects.update(category=None)
    Category.objects.filter(slug__in=[slug for _, slug in CATEGORIES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='events.category'),
        ),
        migrations.RunPython(seed_categories, unseed_categories),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('event', 'user'), name='unique_event_user_favorite')],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('comment', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_reviews', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='events.event')),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('event', 'author'), name='unique_event_author_review'), models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='review_rating_between_one_and_five')],
            },
        ),
    ]
