# Generated by Django 5.2.15 on 2026-07-10 09:49

import django.core.validators
import events.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_category_event_category_favorite_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, upload_to='event_images/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), events.validators.validate_event_image_size]),
        ),
    ]
